import type { Program, Transaction, Certificate } from "@/types";

// ============================================================================
// DATA DUMMY AWAL
// ----------------------------------------------------------------------------
// Semua angka dibuat "masuk akal" untuk yayasan yang baru memulai program
// wakaf digital. `imageUrl` sengaja dikosongkan sehingga tiap program memakai
// ILUSTRASI DUMMY sesuai kategori (components/program-illustration.tsx) —
// TODO(compro): isi dengan URL foto dokumentasi asli begitu materi dari
// yayasan tersedia. Transaksi riwayat sudah berstatus "paid" sejak awal supaya
// halaman Riwayat & Transparansi tidak kosong saat demo pertama kali dibuka.
// ============================================================================

export const SEED_PROGRAMS: Program[] = [
  {
    id: "prg-masjid-albarokah",
    program_type: "wakaf-melalui-uang",
    kategori: "masjid",
    nama: "Pembangunan Masjid Al-Barokah",
    slug: "pembangunan-masjid-al-barokah",
    lokasi: "Rancasari, Kota Bandung",
    ringkasan:
      "Perluasan lantai dua dan fasilitas wudu ramah difabel agar mampu menampung 800 jamaah salat Jumat & pengajian warga.",
    deskripsi:
      "Masjid Al-Barokah berdiri sejak 1998 dan kini tidak lagi mampu menampung jamaah yang terus bertambah. Dana wakaf digunakan untuk perluasan lantai dua, perbaikan atap, sistem tata suara, serta area wudu ramah difabel. Aset wakaf dikelola nazhir resmi dan bersertifikat Badan Wakaf Indonesia.",
    imageUrl: "/images/programs/masjid-albarokah.jpg",
    target: 750_000_000,
    terkumpul: 485_500_000,
    jumlahWakif: 342,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-06-12T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-musala-pesisir",
    program_type: "wakaf-melalui-uang",
    kategori: "masjid",
    nama: "Pembangunan Musala Nelayan Nurul Bahr",
    slug: "pembangunan-musala-nelayan-nurul-bahr",
    lokasi: "Mariso, Kota Makassar",
    ringkasan:
      "Pembangunan sarana ibadah permanen dan tahan abrasi laut bagi 120 kepala keluarga perkampungan nelayan.",
    deskripsi:
      "Musala Nurul Bahr menjadi pusat ibadah dan pembinaan anak-anak perkampungan nelayan pesisir Makassar. Konstruksi dirancang tahan korosi air laut dengan material kayu dan cor beton kokoh. Lahan hibah warga telah diikrarkan sebagai tanah wakaf nazhir.",
    imageUrl: "/images/programs/musala-pesisir.jpg",
    target: 220_000_000,
    terkumpul: 154_200_000,
    jumlahWakif: 189,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-06-18T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-beasiswa-tahfiz",
    program_type: "wakaf-uang",
    kategori: "pendidikan",
    nama: "Wakaf Abadi Beasiswa Santri Tahfiz",
    slug: "wakaf-abadi-beasiswa-santri-tahfiz",
    lokasi: "Sleman, DI Yogyakarta",
    ringkasan:
      "Dana abadi (endowment) untuk beasiswa pendidikan, asrama, dan biaya hidup 50 santri penghafal Al-Qur'an prasejahtera.",
    deskripsi:
      "Wakaf uang dikelola sebagai dana abadi produktif. Hasil pengelolaannya menutup biaya asrama, makan, dan pendidikan santri tahfiz selama satu tahun ajaran. Pokok wakaf tidak berkurang sehingga manfaat mengalir terus-menerus.",
    imageUrl: "/images/programs/beasiswa-tahfiz.jpg",
    target: 500_000_000,
    terkumpul: 312_800_000,
    jumlahWakif: 275,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-06-25T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-rehab-sekolah",
    program_type: "wakaf-melalui-uang",
    kategori: "pendidikan",
    nama: "Rehabilitasi Ruang Kelas MI Nurul Falah",
    slug: "rehabilitasi-ruang-kelas-mi-nurul-falah",
    lokasi: "Praya, Lombok Tengah",
    ringkasan:
      "Renovasi 4 ruang kelas lapuk dan pengadaan 15 unit komputer restored untuk literasi digital siswa madrasah pelosok.",
    deskripsi:
      "Wakaf pembangunan untuk mengganti kuda-kuda atap, plafon, lantai, serta perabot kelas MI Nurul Falah. Bangunan berstatus tanah wakaf resmi dan terdaftar pada Kantor Urusan Agama setempat.",
    imageUrl: "/images/programs/rehab-sekolah.jpg",
    target: 185_000_000,
    terkumpul: 62_400_000,
    jumlahWakif: 84,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-08-01T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-warung-berdaya",
    program_type: "wakaf-uang",
    kategori: "produktif-umkm",
    nama: "Wakaf Modal Bergulir Warung Berdaya",
    slug: "wakaf-modal-bergulir-warung-berdaya",
    lokasi: "Rungkut, Kota Surabaya",
    ringkasan:
      "Modal usaha bergulir tanpa bunga untuk 45 ibu rumah tangga pengusaha mikro binaan kawasan industri perkotaan.",
    deskripsi:
      "Dana wakaf diputar sebagai modal usaha produktif UMKM. Keuntungan dialokasikan kembali untuk pengembangan usaha mitra dan kemaslahatan umat, sementara pokok wakaf tetap terjaga amanah.",
    imageUrl: "/images/programs/warung-berdaya.jpg",
    target: 350_000_000,
    terkumpul: 298_500_000,
    jumlahWakif: 412,
    nazhir: "Nazhir Koperasi Wakaf Nusantara",
    createdAt: "2026-05-30T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-tani-organik",
    program_type: "wakaf-uang",
    kategori: "produktif-umkm",
    nama: "Wakaf Sentra Tani Organik & Greenhouse",
    slug: "wakaf-sentra-tani-organik-greenhouse",
    lokasi: "Lembang, Bandung Barat",
    ringkasan:
      "Pengadaan lahan wakaf pertanian & instalasi hidroponik modern untuk memberdayakan 30 petani muda pedesaan.",
    deskripsi:
      "Program pemberdayaan ekonomi syariah sektor pertanian hidroponik. Hasil panen sayur organik diserap pasar perkotaan dan surplus hasil usaha disalurkan untuk kas sosial yayasan.",
    imageUrl: "/images/programs/tani-organik.jpg",
    target: 400_000_000,
    terkumpul: 180_000_000,
    jumlahWakif: 156,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-07-10T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-sumur-nkri",
    program_type: "wakaf-melalui-uang",
    kategori: "sumur-air-bersih",
    nama: "Wakaf Sumur Bor & Pipanisasi Air Bersih",
    slug: "wakaf-sumur-bor-pipanisasi-air-bersih",
    lokasi: "Tepus, Gunungkidul",
    ringkasan:
      "Pengeboran sumur dalam 120 meter berteknologi surya dan pipanisasi komunal untuk 1.200 jiwa warga rawan air.",
    deskripsi:
      "Dana wakaf membiayai pengeboran sumur dalam, instalasi pompa submersible tenaga surya, tandon penampung, dan jaringan pipa ke titik-titik komunal warga pedesaan Gunungkidul.",
    imageUrl: "/images/programs/sumur-nkri.jpg",
    target: 260_000_000,
    terkumpul: 210_000_000,
    jumlahWakif: 318,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-07-02T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-ambulans-gratis",
    program_type: "wakaf-melalui-uang",
    kategori: "kemanusiaan",
    nama: "Wakaf Ambulans Layanan Umat 24 Jam",
    slug: "wakaf-ambulans-layanan-umat-24-jam",
    lokasi: "Cilincing, Jakarta Utara",
    ringkasan:
      "Pengadaan 1 unit armada ambulans medis komplit tabung oksigen & stretcher gratis untuk tanggap darurat warga dhuafa.",
    deskripsi:
      "Operasional ambulans antar-jemput pasien emergency dan pengantaran jenazah gratis 24 jam penuh untuk keluarga tidak mampu di kawasan padat penduduk Jakarta Utara.",
    imageUrl: "/images/programs/ambulans-gratis.jpg",
    target: 320_000_000,
    terkumpul: 145_000_000,
    jumlahWakif: 203,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-07-20T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-dapur-dhuafa",
    program_type: "infaq-shadaqah",
    kategori: "sosial-dhuafa",
    nama: "Infaq Dapur Umum Berkah 500 Porsi",
    slug: "infaq-dapur-umum-berkah-500-porsi",
    lokasi: "Jatinegara, Jakarta Timur",
    ringkasan:
      "Penyediaan 500 paket makanan siap saji bergizi setiap hari untuk lansia sebatang kara dan pekerja informal.",
    deskripsi:
      "Dana infaq disalurkan langsung secara berkala dalam bentuk makanan sehat siap santap. Tim relawan dapur umum beroperasi tiap hari mengolah bahan segar dan mendistribusikannya.",
    imageUrl: "/images/programs/dapur-dhuafa.jpg",
    target: 120_000_000,
    terkumpul: 84_600_000,
    jumlahWakif: 510,
    nazhir: "Tim Penyalur KBM",
    createdAt: "2026-07-15T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-zakat-asnaf",
    program_type: "zakat",
    kategori: "sosial-dhuafa",
    nama: "Zakat Maal Pemberdayaan 8 Asnaf",
    slug: "zakat-maal-pemberdayaan-8-asnaf",
    lokasi: "Nasional",
    ringkasan:
      "Penyaluran dana zakat harta bagi 8 asnaf penerima manfaat sesuai ketetapan syariat Islam.",
    deskripsi:
      "Himpunan zakat maal & profesi yang disalurkan secara amanah untuk fakir, miskin, gharimin, mualaf, dan asnaf terpilih melalui bantuan pemenuhan modal dasar dan beasiswa Ibnu Sabil.",
    imageUrl: "/images/programs/zakat-asnaf.jpg",
    target: 600_000_000,
    terkumpul: 420_000_000,
    jumlahWakif: 680,
    nazhir: "Amil Zakat KBM",
    createdAt: "2026-07-01T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-klinik-dhuafa",
    program_type: "wakaf-melalui-uang",
    kategori: "kemanusiaan",
    nama: "Wakaf Alat Kesehatan Klinik Pratama Dhuafa",
    slug: "wakaf-alat-kesehatan-klinik-pratama-dhuafa",
    lokasi: "Tambora, Jakarta Barat",
    ringkasan:
      "Pengadaan USG 4D, alat EKG, dan 5 unit bed rawat inap untuk layanan kesehatan gratis warga kurang mampu.",
    deskripsi:
      "Pengadaan alat medis modern guna menunjang klinik gratis bagi warga kurang mampu di kawasan padat penduduk Tambora. Layanan mencakup cek kesehatan, persalinan, dan pengobatan gratis.",
    imageUrl: "/images/programs/ambulans-gratis.jpg",
    target: 450_000_000,
    terkumpul: 230_000_000,
    jumlahWakif: 195,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-07-25T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-taman-baca",
    program_type: "wakaf-melalui-uang",
    kategori: "pendidikan",
    nama: "Wakaf Rumah Literasi & Perpustakaan Digital Anak",
    slug: "wakaf-rumah-literasi-perpustakaan-digital-anak",
    lokasi: "Sentani, Kabupaten Jayapura",
    ringkasan:
      "Pembangunan gedung perpustakaan ramah anak dan 20 komputer tablet berisi rujukan edukasi islami & umum.",
    deskripsi:
      "Menyediakan akses bacaan berkualitas dan edukasi digital gratis bagi anak-anak di daerah pesisir Danau Sentani untuk meningkatkan minat baca dan wawasan kebangsaan.",
    imageUrl: "/images/programs/rehab-sekolah.jpg",
    target: 210_000_000,
    terkumpul: 165_000_000,
    jumlahWakif: 142,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-08-02T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-zakat-profesi",
    program_type: "zakat",
    kategori: "sosial-dhuafa",
    nama: "Zakat Profesi & Penghasilan Modal Usaha Mustahik",
    slug: "zakat-profesi-penghasilan-modal-usaha-mustahik",
    lokasi: "DKI Jakarta & Sekitarnya",
    ringkasan:
      "Optimalisasi penyerapan zakat profesi ASN & karyawan swasta untuk modal usaha mikro 100 keluarga mustahik.",
    deskripsi:
      "Dana zakat penghasilan yang disalurkan dalam bentuk gerobak usaha dan modal awal usaha bagi keluarga kurang mampu agar mandiri secara ekonomi.",
    imageUrl: "/images/programs/zakat-asnaf.jpg",
    target: 350_000_000,
    terkumpul: 280_000_000,
    jumlahWakif: 410,
    nazhir: "Amil Zakat KBM",
    createdAt: "2026-08-05T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-infaq-jumat",
    program_type: "infaq-shadaqah",
    kategori: "sosial-dhuafa",
    nama: "Infaq Sedekah Jumat Berkah 1.000 Paket Sembako",
    slug: "infaq-sedekah-jumat-berkah-1000-paket-sembako",
    lokasi: "Depok, Jawa Barat",
    ringkasan:
      "Pembagian paket beras, minyak goreng, dan telur untuk lansia dhuafa dan janda miskin setiap hari Jumat.",
    deskripsi:
      "Program infaq rutin mingguan untuk menjangkau warga lansia sebatang kara di pemukiman padat Depok agar kebutuhan pangan dasar mereka terpenuhi.",
    imageUrl: "/images/programs/dapur-dhuafa.jpg",
    target: 95_000_000,
    terkumpul: 72_000_000,
    jumlahWakif: 380,
    nazhir: "Tim Penyalur KBM",
    createdAt: "2026-08-10T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-pesantren-tahfiz",
    program_type: "wakaf-melalui-uang",
    kategori: "pendidikan",
    nama: "Wakaf Pembangunan Asrama Santri Yatim & Dhuafa",
    slug: "wakaf-pembangunan-asrama-santri-yatim-dhuafa",
    lokasi: "Cisarua, Kabupaten Bogor",
    ringkasan:
      "Pembangunan gedung 3 lantai asrama santri gratis berkapasitas 150 santri binaan yayasan.",
    deskripsi:
      "Membangun fasilitas tempat tinggal yang layak, bersih, dan nyaman bagi anak-anak yatim dan dhuafa yang menempuh pendidikan tahfiz di kawasan Bogor.",
    imageUrl: "/images/programs/beasiswa-tahfiz.jpg",
    target: 850_000_000,
    terkumpul: 520_000_000,
    jumlahWakif: 490,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-06-05T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-peternakan-kambing",
    program_type: "wakaf-uang",
    kategori: "produktif-umkm",
    nama: "Wakaf Sentra Peternakan Kambing Produktif Umat",
    slug: "wakaf-sentra-peternakan-kambing-produktif-umat",
    lokasi: "Boyolali, Jawa Tengah",
    ringkasan:
      "Pengembangan peternakan 200 ekor kambing etawa untuk pasokan kurban & aqiqah berbasis bagi hasil peternak.",
    deskripsi:
      "Modal wakaf uang produktif yang dikelola untuk peternakan kambing berkualitas. Hasil usaha dibagi hasilkan dengan warga lokal dan surplusnya disalurkan untuk beasiswa.",
    imageUrl: "/images/programs/tani-organik.jpg",
    target: 450_000_000,
    terkumpul: 290_000_000,
    jumlahWakif: 230,
    nazhir: "Nazhir Koperasi Wakaf Nusantara",
    createdAt: "2026-06-20T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-musholla-transit",
    program_type: "wakaf-melalui-uang",
    kategori: "masjid",
    nama: "Wakaf Musala Transit Jalur Mudik & Musafir",
    slug: "wakaf-musala-transit-jalur-mudik-musafir",
    lokasi: "Bakauheni, Lampung Selatan",
    ringkasan:
      "Fasilitas tempat ibadah 24 jam yang bersih, toilet nyaman, dan rest area gratis bagi para pemudik & musafir.",
    deskripsi:
      "Membangun musala dan tempat istirahat ramah musafir di jalur utama pelabuhan Bakauheni untuk memberikan kenyamanan beribadah bagi masyarakat yang bepergian.",
    imageUrl: "/images/programs/musala-pesisir.jpg",
    target: 280_000_000,
    terkumpul: 195_000_000,
    jumlahWakif: 215,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-07-05T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-beasiswa-sarjana",
    program_type: "wakaf-uang",
    kategori: "pendidikan",
    nama: "Wakaf Dana Abadi Beasiswa Mahasiswa Prestasi Pelosok",
    slug: "wakaf-dana-abadi-beasiswa-mahasiswa-prestasi-pelosok",
    lokasi: "Bandung, Jawa Barat",
    ringkasan:
      "Dana endowment untuk pembiayaan kuliah UKT 20 mahasiswa yatim berprestasi di perguruan tinggi negeri.",
    deskripsi:
      "Wakaf dana abadi pendidikan yang dikembangkan secara amanah syariah untuk membiayai kuliah anak-anak cerdas berprestasi dari daerah pelosok hingga lulus sarjana.",
    imageUrl: "/images/programs/beasiswa-tahfiz.jpg",
    target: 600_000_000,
    terkumpul: 410_000_000,
    jumlahWakif: 360,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-07-12T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-kemanusiaan-bencana",
    program_type: "infaq-shadaqah",
    kategori: "kemanusiaan",
    nama: "Infaq Tanggap Darurat & Posko Medis Bencana Alam",
    slug: "infaq-tanggap-darurat-posko-medis-bencana-alam",
    lokasi: "Cianjur, Jawa Barat",
    ringkasan:
      "Pengadaan selimut, tenda pengungsian, dan dapur air darurat saat terjadi bencana alam hidrometeorologi.",
    deskripsi:
      "Dana kesiapsiagaan tanggap bencana untuk pertolongan cepat, bantuan medis darurat, serta pasokan bahan pokok bagi pengungsi korban bencana alam.",
    imageUrl: "/images/programs/ambulans-gratis.jpg",
    target: 150_000_000,
    terkumpul: 115_000_000,
    jumlahWakif: 420,
    nazhir: "Tim Penyalur KBM",
    createdAt: "2026-08-15T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-zakat-fitrah-perdagangan",
    program_type: "zakat",
    kategori: "produktif-umkm",
    nama: "Zakat Perdagangan Pembebasan Utang Riba Mustahik",
    slug: "zakat-perdagangan-pembebasan-utang-riba-mustahik",
    lokasi: "Semarang, Jawa Tengah",
    ringkasan:
      "Penyaluran zakat khusus gharimin guna membebaskan pedagang kecil dari jeratan pinjaman online & rentenir.",
    deskripsi:
      "Bantuan pendampingan keuangan dan pelunasan utang tercekik bagi pengusaha mikro pasar tradisional agar dapat kembali berjualan dengan tenang.",
    imageUrl: "/images/programs/warung-berdaya.jpg",
    target: 300_000_000,
    terkumpul: 245_000_000,
    jumlahWakif: 310,
    nazhir: "Amil Zakat KBM",
    createdAt: "2026-08-18T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-masjid-jogja",
    program_type: "wakaf-melalui-uang",
    kategori: "masjid",
    nama: "Wakaf Karpet & Sound System Masjid Jami Nurul Huda",
    slug: "wakaf-karpet-sound-system-masjid-jami-nurul-huda",
    lokasi: "Kotagede, Yogyakarta",
    ringkasan:
      "Pengadaan karpet tebal impor dan peremajaan sistem tata suara masjid bersejarah di kawasan Kotagede.",
    deskripsi:
      "Meningkatkan kekhusyukan jamaah salat lima waktu dan kegiatan kaji keislaman melalui perbaikan fasilitas akustik dan alas salat yang empuk dan bersih.",
    imageUrl: "/images/programs/masjid-albarokah.jpg",
    target: 175_000_000,
    terkumpul: 132_000_000,
    jumlahWakif: 178,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-08-20T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
];

// ----------------------------------------------------------------------------
// Transaksi riwayat dummy (sudah selesai). Dua di antaranya memakai email
// "wakif@contoh.id" agar mudah dipakai saat mendemokan halaman Riwayat.
// ----------------------------------------------------------------------------
export const SEED_TRANSACTIONS: Transaction[] = [
  {
    id: "WKF-20260710-7QK2ZP",
    program_type: "wakaf-melalui-uang",
    programId: "prg-masjid-albarokah",
    programNama: "Pembangunan Masjid Al-Barokah",
    nominal: 1_000_000,
    biayaAdmin: 0,
    total: 1_000_000,
    namaWakif: "Ahmad Fauzi",
    emailWakif: "wakif@contoh.id",
    teleponWakif: "081234567001",
    atasNama: "sendiri",
    visibilitas: "publik",
    doa: "Semoga menjadi amal jariyah yang tak terputus.",
    vaNumber: "DEMO 1234 5670 0120",
    bank: "BSI",
    status: "paid",
    createdAt: "2026-07-10T03:10:00.000Z",
    expiresAt: "2026-07-11T03:10:00.000Z",
    paidAt: "2026-07-10T03:24:00.000Z",
    certificateId: "SW/2026/07/000001",
  },
  {
    id: "WKF-20260722-M4TR8A",
    program_type: "wakaf-uang",
    programId: "prg-warung-berdaya",
    programNama: "Wakaf Modal Bergulir Warung Berdaya",
    nominal: 500_000,
    biayaAdmin: 0,
    total: 500_000,
    namaWakif: "Siti Nurhaliza",
    emailWakif: "wakif@contoh.id",
    teleponWakif: "081234567002",
    atasNama: "orang-lain",
    namaAtasNama: "Almh. Hj. Rukmini",
    visibilitas: "anonim",
    doa: "Untuk almarhumah ibunda tercinta.",
    vaNumber: "DEMO 9876 5430 0210",
    bank: "Mandiri",
    status: "paid",
    createdAt: "2026-07-22T06:40:00.000Z",
    expiresAt: "2026-07-23T06:40:00.000Z",
    paidAt: "2026-07-22T07:02:00.000Z",
    certificateId: "SW/2026/07/000002",
  },
  {
    id: "WKF-20260805-JD91KE",
    program_type: "wakaf-melalui-uang",
    programId: "prg-sumur-nkri",
    programNama: "Wakaf Sumur Bor & Pipanisasi Air Bersih",
    nominal: 2_500_000,
    biayaAdmin: 0,
    total: 2_500_000,
    namaWakif: "Budi Santoso",
    emailWakif: "budi.santoso@contoh.id",
    teleponWakif: "081234567003",
    atasNama: "sendiri",
    visibilitas: "publik",
    vaNumber: "DEMO 1122 3340 0310",
    bank: "BCA",
    status: "paid",
    createdAt: "2026-08-05T01:15:00.000Z",
    expiresAt: "2026-08-06T01:15:00.000Z",
    paidAt: "2026-08-05T01:40:00.000Z",
    certificateId: "SW/2026/08/000003",
  },
  {
    id: "WKF-20260819-P05WQN",
    program_type: "wakaf-melalui-uang",
    programId: "prg-musala-pesisir",
    programNama: "Pembangunan Musala Nelayan Nurul Bahr",
    nominal: 750_000,
    biayaAdmin: 0,
    total: 750_000,
    namaWakif: "Dewi Lestari",
    emailWakif: "dewi.lestari@contoh.id",
    teleponWakif: "081234567004",
    atasNama: "sendiri",
    visibilitas: "publik",
    doa: "Semoga jamaah selalu diberi keberkahan rezeki.",
    vaNumber: "DEMO 5566 7780 0410",
    bank: "BNI",
    status: "paid",
    createdAt: "2026-08-19T08:05:00.000Z",
    expiresAt: "2026-08-20T08:05:00.000Z",
    paidAt: "2026-08-19T08:30:00.000Z",
    certificateId: "SW/2026/08/000004",
  },
  {
    id: "WKF-20260828-R3NX7C",
    program_type: "infaq-shadaqah",
    programId: "prg-dapur-dhuafa",
    programNama: "Infaq Dapur Umum Berkah 500 Porsi",
    nominal: 150_000,
    biayaAdmin: 0,
    total: 150_000,
    namaWakif: "Rahmat Hidayat",
    emailWakif: "rahmat.hidayat@contoh.id",
    teleponWakif: "081234567005",
    atasNama: "sendiri",
    visibilitas: "publik",
    doa: "Semoga cukup untuk sepuluh porsi hari ini.",
    vaNumber: "DEMO 3344 5560 0510",
    bank: "BRI",
    status: "paid",
    createdAt: "2026-08-28T02:20:00.000Z",
    expiresAt: "2026-08-29T02:20:00.000Z",
    paidAt: "2026-08-28T02:35:00.000Z",
    certificateId: "SW/2026/08/000005",
  },
  {
    id: "WKF-20260901-T8VK2M",
    program_type: "zakat",
    programId: "prg-zakat-asnaf",
    programNama: "Zakat Maal Pemberdayaan 8 Asnaf",
    nominal: 3_250_000,
    biayaAdmin: 0,
    total: 3_250_000,
    namaWakif: "Hendra Kurniawan",
    emailWakif: "wakif@contoh.id",
    teleponWakif: "081234567006",
    atasNama: "sendiri",
    visibilitas: "anonim",
    vaNumber: "DEMO 7788 9900 0610",
    bank: "BSI",
    status: "paid",
    createdAt: "2026-09-01T04:10:00.000Z",
    expiresAt: "2026-09-02T04:10:00.000Z",
    paidAt: "2026-09-01T04:28:00.000Z",
    certificateId: "SW/2026/09/000006",
  },
];

export const SEED_CERTIFICATES: Certificate[] = SEED_TRANSACTIONS.map((t) => ({
  id: t.certificateId!,
  transactionId: t.id,
  programId: t.programId,
  programNama: t.programNama,
  program_type: t.program_type,
  namaPihak: t.atasNama === "orang-lain" && t.namaAtasNama ? t.namaAtasNama : t.namaWakif,
  nominal: t.nominal,
  tanggal: t.paidAt!,
  nazhir:
    SEED_PROGRAMS.find((p) => p.id === t.programId)?.nazhir ??
    "Nazhir Yayasan Khazanah Berkah Mulia",
}));

// Nomor urut sertifikat berikutnya (lanjut dari seed).
export const SEED_CERT_SEQ = SEED_CERTIFICATES.length; // -> 4
