export const programSchemas = {
  ProgramType: {
    type: "string",
    enum: [
      "wakaf-uang",
      "wakaf-melalui-uang",
      "infaq-shadaqah",
      "zakat",
    ],
    example: "wakaf-melalui-uang",
    description: "Kategori instrumen filantropi Islam.",
  },
  Program: {
    type: "object",
    description: "Model representasi program wakaf / donasi.",
    properties: {
      id: { type: "string", example: "prg_f9a75a05f82e" },
      program_type: { $ref: "#/components/schemas/ProgramType" },
      kategori: { type: "string", example: "masjid" },
      nama: { type: "string", example: "Pembangunan Masjid Al-Barkah" },
      slug: { type: "string", example: "pembangunan-masjid-al-barkah" },
      lokasi: { type: "string", example: "Bandung, Jawa Barat" },
      ringkasan: { type: "string", example: "Penyediaan fasilitas ibadah yang layak." },
      deskripsi: { type: "string", example: "Deskripsi lengkap program pembangunan..." },
      imageUrl: { type: "string", example: "https://blob.../image.jpg" },
      target: { type: "number", example: 50000000 },
      terkumpul: { type: "number", example: 12500000 },
      jumlahWakif: { type: "number", example: 28 },
      nazhir: { type: "string", example: "Nazhir Yayasan Khazanah Berkah Mulia" },
      createdAt: { type: "string", format: "date-time" },
      aktif: { type: "boolean", example: true },
      disbursements: {
        type: "array",
        items: { $ref: "#/components/schemas/DisbursementReport" },
      },
    },
    required: [
      "id",
      "program_type",
      "kategori",
      "nama",
      "slug",
      "lokasi",
      "ringkasan",
      "deskripsi",
      "target",
      "terkumpul",
      "jumlahWakif",
      "aktif",
    ],
  },
  CreateProgramInput: {
    type: "object",
    description: "Payload pembuatan program baru.",
    properties: {
      program_type: { $ref: "#/components/schemas/ProgramType" },
      kategori: { type: "string", example: "masjid" },
      nama: { type: "string", example: "Pembangunan Sarana Air Bersih" },
      lokasi: { type: "string", example: "Gunungkidul, DIY" },
      ringkasan: { type: "string", example: "Penyediaan sumur bor dan pipanisasi warga." },
      deskripsi: { type: "string", example: "Program penyediaan air bersih berkelanjutan..." },
      target: { type: "number", example: 35000000 },
      imageUrl: { type: "string", example: "https://blob.../sumur.jpg" },
    },
    required: ["program_type", "kategori", "nama", "lokasi", "ringkasan", "deskripsi", "target"],
  },
  UpdateProgramInput: {
    type: "object",
    description: "Payload pembaruan data program.",
    properties: {
      program_type: { $ref: "#/components/schemas/ProgramType" },
      kategori: { type: "string" },
      nama: { type: "string" },
      lokasi: { type: "string" },
      ringkasan: { type: "string" },
      deskripsi: { type: "string" },
      target: { type: "number" },
      imageUrl: { type: "string" },
      aktif: { type: "boolean" },
    },
  },
};
