export const transactionSchemas = {
  Transaction: {
    type: "object",
    description: "Model transaksi donasi/wakaf.",
    properties: {
      id: { type: "string", example: "WKF-20260914-321916" },
      program_type: { $ref: "#/components/schemas/ProgramType" },
      programId: { type: "string", example: "prg_f9a75a05f82e" },
      programNama: { type: "string", example: "Pembangunan Masjid Al-Barkah" },
      nominal: { type: "number", example: 1000000 },
      biayaAdmin: { type: "number", example: 0 },
      total: { type: "number", example: 1000000 },
      namaWakif: { type: "string", example: "Ahmad Fauzi" },
      emailWakif: { type: "string", format: "email", example: "ahmad@example.com" },
      teleponWakif: { type: "string", example: "+628123456789" },
      atasNama: { type: "string", enum: ["sendiri", "orang-lain"], example: "sendiri" },
      namaAtasNama: { type: "string", nullable: true, example: null },
      visibilitas: { type: "string", enum: ["publik", "anonim"], example: "publik" },
      doa: { type: "string", nullable: true, example: "Semoga berkah untuk umat." },
      vaNumber: { type: "string", example: "70019936642468" },
      bank: { type: "string", example: "BSI" },
      status: {
        type: "string",
        enum: ["pending", "paid", "expired"],
        example: "pending",
      },
      createdAt: { type: "string", format: "date-time" },
      expiresAt: { type: "string", format: "date-time" },
      paidAt: { type: "string", format: "date-time", nullable: true },
      certificateId: { type: "string", nullable: true, example: "SW/2026/09/FEFF7D" },
      snapToken: { type: "string", nullable: true },
      snapRedirectUrl: { type: "string", nullable: true },
    },
    required: [
      "id",
      "program_type",
      "programId",
      "programNama",
      "nominal",
      "total",
      "namaWakif",
      "emailWakif",
      "teleponWakif",
      "atasNama",
      "visibilitas",
      "status",
      "createdAt",
      "expiresAt",
    ],
  },
  CreateTransactionInput: {
    type: "object",
    description: "Payload inisiasi donasi / wakaf baru.",
    properties: {
      programId: { type: "string", example: "prg_f9a75a05f82e" },
      nominal: { type: "number", minimum: 10000, example: 500000 },
      namaWakif: { type: "string", example: "Ahmad Fauzi" },
      emailWakif: { type: "string", format: "email", example: "ahmad@example.com" },
      teleponWakif: { type: "string", example: "081234567890" },
      atasNama: { type: "string", enum: ["sendiri", "orang-lain"], default: "sendiri" },
      namaAtasNama: { type: "string" },
      visibilitas: { type: "string", enum: ["publik", "anonim"], default: "publik" },
      doa: { type: "string", example: "Semoga berkah dan menjadi amal jariyah." },
    },
    required: ["programId", "nominal", "namaWakif", "emailWakif", "teleponWakif"],
  },
};
