import type { Program, Transaction, Certificate } from "@/types";

// ============================================================================
// DATA DUMMY AWAL
// ----------------------------------------------------------------------------
// Semua angka dibuat "masuk akal" untuk yayasan yang baru memulai program
// wakaf digital. `imageUrl` sengaja dikosongkan sehingga tiap program memakai
// ILUSTRASI DUMMY sesuai kategori (components/program-illustration.tsx) —
// TODO(compro): isi dengan URL foto dokumentasi asli begitu materi dari
// yayasan tersedia. Transaksi riwayat sudah berstatus "paid" sejak awal supaya
// halaman Riwayat & Transparansi tidak kosong saat demo pertama kali dibuka.
// ============================================================================

export const SEED_PROGRAMS: Program[] = [
  {
    id: "prg-masjid-albarokah",
    program_type: "wakaf-melalui-uang",
    kategori: "masjid",
    nama: "Pembangunan Masjid Al-Barokah",
    slug: "pembangunan-masjid-al-barokah",
    lokasi: "Rancasari, Kota Bandung",
    ringkasan:
      "Perluasan lantai dua dan fasilitas wudu ramah difabel agar mampu menampung 800 jamaah salat Jumat & pengajian warga.",
    deskripsi:
      "Masjid Al-Barokah berdiri sejak 1998 dan kini tidak lagi mampu menampung jamaah yang terus bertambah. Dana wakaf digunakan untuk perluasan lantai dua, perbaikan atap, sistem tata suara, serta area wudu ramah difabel. Aset wakaf dikelola nazhir resmi dan bersertifikat Badan Wakaf Indonesia.",
    imageUrl: "/images/programs/masjid-albarokah.jpg",
    target: 750_000_000,
    terkumpul: 485_500_000,
    jumlahWakif: 342,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-06-12T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-musala-pesisir",
    program_type: "wakaf-melalui-uang",
    kategori: "masjid",
    nama: "Pembangunan Musala Nelayan Nurul Bahr",
    slug: "pembangunan-musala-nelayan-nurul-bahr",
    lokasi: "Mariso, Kota Makassar",
    ringkasan:
      "Pembangunan sarana ibadah permanen dan tahan abrasi laut bagi 120 kepala keluarga perkampungan nelayan.",
    deskripsi:
      "Musala Nurul Bahr menjadi pusat ibadah dan pembinaan anak-anak perkampungan nelayan pesisir Makassar. Konstruksi dirancang tahan korosi air laut dengan material kayu dan cor beton kokoh. Lahan hibah warga telah diikrarkan sebagai tanah wakaf nazhir.",
    imageUrl: "/images/programs/musala-pesisir.jpg",
    target: 220_000_000,
    terkumpul: 154_200_000,
    jumlahWakif: 189,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-06-18T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-beasiswa-tahfiz",
    program_type: "wakaf-uang",
    kategori: "pendidikan",
    nama: "Wakaf Abadi Beasiswa Santri Tahfiz",
    slug: "wakaf-abadi-beasiswa-santri-tahfiz",
    lokasi: "Sleman, DI Yogyakarta",
    ringkasan:
      "Dana abadi (endowment) untuk beasiswa pendidikan, asrama, dan biaya hidup 50 santri penghafal Al-Qur'an prasejahtera.",
    deskripsi:
      "Wakaf uang dikelola sebagai dana abadi produktif. Hasil pengelolaannya menutup biaya asrama, makan, dan pendidikan santri tahfiz selama satu tahun ajaran. Pokok wakaf tidak berkurang sehingga manfaat mengalir terus-menerus.",
    imageUrl: "/images/programs/beasiswa-tahfiz.jpg",
    target: 500_000_000,
    terkumpul: 312_800_000,
    jumlahWakif: 275,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-06-25T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-rehab-sekolah",
    program_type: "wakaf-melalui-uang",
    kategori: "pendidikan",
    nama: "Rehabilitasi Ruang Kelas MI Nurul Falah",
    slug: "rehabilitasi-ruang-kelas-mi-nurul-falah",
    lokasi: "Praya, Lombok Tengah",
    ringkasan:
      "Renovasi 4 ruang kelas lapuk dan pengadaan 15 unit komputer restored untuk literasi digital siswa madrasah pelosok.",
    deskripsi:
      "Wakaf pembangunan untuk mengganti kuda-kuda atap, plafon, lantai, serta perabot kelas MI Nurul Falah. Bangunan berstatus tanah wakaf resmi dan terdaftar pada Kantor Urusan Agama setempat.",
    imageUrl: "/images/programs/rehab-sekolah.jpg",
    target: 185_000_000,
    terkumpul: 62_400_000,
    jumlahWakif: 84,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-08-01T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-warung-berdaya",
    program_type: "wakaf-uang",
    kategori: "produktif-umkm",
    nama: "Wakaf Modal Bergulir Warung Berdaya",
    slug: "wakaf-modal-bergulir-warung-berdaya",
    lokasi: "Rungkut, Kota Surabaya",
    ringkasan:
      "Modal usaha bergulir tanpa bunga untuk 45 ibu rumah tangga pengusaha mikro binaan kawasan industri perkotaan.",
    deskripsi:
      "Dana wakaf diputar sebagai modal usaha produktif UMKM. Keuntungan dialokasikan kembali untuk pengembangan usaha mitra dan kemaslahatan umat, sementara pokok wakaf tetap terjaga amanah.",
    imageUrl: "/images/programs/warung-berdaya.jpg",
    target: 350_000_000,
    terkumpul: 298_500_000,
    jumlahWakif: 412,
    nazhir: "Nazhir Koperasi Wakaf Nusantara",
    createdAt: "2026-05-30T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-tani-organik",
    program_type: "wakaf-uang",
    kategori: "produktif-umkm",
    nama: "Wakaf Sentra Tani Organik & Greenhouse",
    slug: "wakaf-sentra-tani-organik-greenhouse",
    lokasi: "Lembang, Bandung Barat",
    ringkasan:
      "Pengadaan lahan wakaf pertanian & instalasi hidroponik modern untuk memberdayakan 30 petani muda pedesaan.",
    deskripsi:
      "Program pemberdayaan ekonomi syariah sektor pertanian hidroponik. Hasil panen sayur organik diserap pasar perkotaan dan surplus hasil usaha disalurkan untuk kas sosial yayasan.",
    imageUrl: "/images/programs/tani-organik.jpg",
    target: 400_000_000,
    terkumpul: 180_000_000,
    jumlahWakif: 156,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-07-10T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-sumur-nkri",
    program_type: "wakaf-melalui-uang",
    kategori: "sumur-air-bersih",
    nama: "Wakaf Sumur Bor & Pipanisasi Air Bersih",
    slug: "wakaf-sumur-bor-pipanisasi-air-bersih",
    lokasi: "Tepus, Gunungkidul",
    ringkasan:
      "Pengeboran sumur dalam 120 meter berteknologi surya dan pipanisasi komunal untuk 1.200 jiwa warga rawan air.",
    deskripsi:
      "Dana wakaf membiayai pengeboran sumur dalam, instalasi pompa submersible tenaga surya, tandon penampung, dan jaringan pipa ke titik-titik komunal warga pedesaan Gunungkidul.",
    imageUrl: "/images/programs/sumur-nkri.jpg",
    target: 260_000_000,
    terkumpul: 210_000_000,
    jumlahWakif: 318,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-07-02T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-ambulans-gratis",
    program_type: "wakaf-melalui-uang",
    kategori: "kemanusiaan",
    nama: "Wakaf Ambulans Layanan Umat 24 Jam",
    slug: "wakaf-ambulans-layanan-umat-24-jam",
    lokasi: "Cilincing, Jakarta Utara",
    ringkasan:
      "Pengadaan 1 unit armada ambulans medis komplit tabung oksigen & stretcher gratis untuk tanggap darurat warga dhuafa.",
    deskripsi:
      "Operasional ambulans antar-jemput pasien emergency dan pengantaran jenazah gratis 24 jam penuh untuk keluarga tidak mampu di kawasan padat penduduk Jakarta Utara.",
    imageUrl: "/images/programs/ambulans-gratis.jpg",
    target: 320_000_000,
    terkumpul: 145_000_000,
    jumlahWakif: 203,
    nazhir: "Nazhir Yayasan Khazanah Berkah Mulia",
    createdAt: "2026-07-20T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-dapur-dhuafa",
    program_type: "infaq-shadaqah",
    kategori: "sosial-dhuafa",
    nama: "Infaq Dapur Umum Berkah 500 Porsi",
    slug: "infaq-dapur-umum-berkah-500-porsi",
    lokasi: "Jatinegara, Jakarta Timur",
    ringkasan:
      "Penyediaan 500 paket makanan siap saji bergizi setiap hari untuk lansia sebatang kara dan pekerja informal.",
    deskripsi:
      "Dana infaq disalurkan langsung secara berkala dalam bentuk makanan sehat siap santap. Tim relawan dapur umum beroperasi tiap hari mengolah bahan segar dan mendistribusikannya.",
    imageUrl: "/images/programs/dapur-dhuafa.jpg",
    target: 120_000_000,
    terkumpul: 84_600_000,
    jumlahWakif: 510,
    nazhir: "Tim Penyalur KBM",
    createdAt: "2026-07-15T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
  {
    id: "prg-zakat-asnaf",
    program_type: "zakat",
    kategori: "sosial-dhuafa",
    nama: "Zakat Maal Pemberdayaan 8 Asnaf",
    slug: "zakat-maal-pemberdayaan-8-asnaf",
    lokasi: "Nasional",
    ringkasan:
      "Penyaluran dana zakat harta bagi 8 asnaf penerima manfaat sesuai ketetapan syariat Islam.",
    deskripsi:
      "Himpunan zakat maal & profesi yang disalurkan secara amanah untuk fakir, miskin, gharimin, mualaf, dan asnaf terpilih melalui bantuan pemenuhan modal dasar dan beasiswa Ibnu Sabil.",
    imageUrl: "/images/programs/zakat-asnaf.jpg",
    target: 600_000_000,
    terkumpul: 420_000_000,
    jumlahWakif: 680,
    nazhir: "Amil Zakat KBM",
    createdAt: "2026-07-01T02:00:00.000Z",
    aktif: true,
    disbursements: [],
  },
];

// ----------------------------------------------------------------------------
// Transaksi riwayat dummy (sudah selesai). Dua di antaranya memakai email
// "wakif@contoh.id" agar mudah dipakai saat mendemokan halaman Riwayat.
// ----------------------------------------------------------------------------
export const SEED_TRANSACTIONS: Transaction[] = [
  {
    id: "WKF-20260710-7QK2ZP",
    program_type: "wakaf-melalui-uang",
    programId: "prg-masjid-albarokah",
    programNama: "Pembangunan Masjid Al-Barokah",
    nominal: 1_000_000,
    biayaAdmin: 0,
    total: 1_000_000,
    namaWakif: "Ahmad Fauzi",
    emailWakif: "wakif@contoh.id",
    teleponWakif: "081234567001",
    atasNama: "sendiri",
    visibilitas: "publik",
    doa: "Semoga menjadi amal jariyah yang tak terputus.",
    vaNumber: "DEMO 1234 5670 0120",
    bank: "BSI",
    status: "paid",
    createdAt: "2026-07-10T03:10:00.000Z",
    expiresAt: "2026-07-11T03:10:00.000Z",
    paidAt: "2026-07-10T03:24:00.000Z",
    certificateId: "SW/2026/07/000001",
  },
  {
    id: "WKF-20260722-M4TR8A",
    program_type: "wakaf-uang",
    programId: "prg-warung-berdaya",
    programNama: "Wakaf Modal Bergulir Warung Berdaya",
    nominal: 500_000,
    biayaAdmin: 0,
    total: 500_000,
    namaWakif: "Siti Nurhaliza",
    emailWakif: "wakif@contoh.id",
    teleponWakif: "081234567002",
    atasNama: "orang-lain",
    namaAtasNama: "Almh. Hj. Rukmini",
    visibilitas: "anonim",
    doa: "Untuk almarhumah ibunda tercinta.",
    vaNumber: "DEMO 9876 5430 0210",
    bank: "Mandiri",
    status: "paid",
    createdAt: "2026-07-22T06:40:00.000Z",
    expiresAt: "2026-07-23T06:40:00.000Z",
    paidAt: "2026-07-22T07:02:00.000Z",
    certificateId: "SW/2026/07/000002",
  },
  {
    id: "WKF-20260805-JD91KE",
    program_type: "wakaf-melalui-uang",
    programId: "prg-sumur-nkri",
    programNama: "Wakaf Sumur Bor & Pipanisasi Air Bersih",
    nominal: 2_500_000,
    biayaAdmin: 0,
    total: 2_500_000,
    namaWakif: "Budi Santoso",
    emailWakif: "budi.santoso@contoh.id",
    teleponWakif: "081234567003",
    atasNama: "sendiri",
    visibilitas: "publik",
    vaNumber: "DEMO 1122 3340 0310",
    bank: "BCA",
    status: "paid",
    createdAt: "2026-08-05T01:15:00.000Z",
    expiresAt: "2026-08-06T01:15:00.000Z",
    paidAt: "2026-08-05T01:40:00.000Z",
    certificateId: "SW/2026/08/000003",
  },
  {
    id: "WKF-20260819-P05WQN",
    program_type: "wakaf-melalui-uang",
    programId: "prg-musala-pesisir",
    programNama: "Pembangunan Musala Nelayan Nurul Bahr",
    nominal: 750_000,
    biayaAdmin: 0,
    total: 750_000,
    namaWakif: "Dewi Lestari",
    emailWakif: "dewi.lestari@contoh.id",
    teleponWakif: "081234567004",
    atasNama: "sendiri",
    visibilitas: "publik",
    doa: "Semoga jamaah selalu diberi keberkahan rezeki.",
    vaNumber: "DEMO 5566 7780 0410",
    bank: "BNI",
    status: "paid",
    createdAt: "2026-08-19T08:05:00.000Z",
    expiresAt: "2026-08-20T08:05:00.000Z",
    paidAt: "2026-08-19T08:30:00.000Z",
    certificateId: "SW/2026/08/000004",
  },
  {
    id: "WKF-20260828-R3NX7C",
    program_type: "infaq-shadaqah",
    programId: "prg-dapur-dhuafa",
    programNama: "Infaq Dapur Umum Berkah 500 Porsi",
    nominal: 150_000,
    biayaAdmin: 0,
    total: 150_000,
    namaWakif: "Rahmat Hidayat",
    emailWakif: "rahmat.hidayat@contoh.id",
    teleponWakif: "081234567005",
    atasNama: "sendiri",
    visibilitas: "publik",
    doa: "Semoga cukup untuk sepuluh porsi hari ini.",
    vaNumber: "DEMO 3344 5560 0510",
    bank: "BRI",
    status: "paid",
    createdAt: "2026-08-28T02:20:00.000Z",
    expiresAt: "2026-08-29T02:20:00.000Z",
    paidAt: "2026-08-28T02:35:00.000Z",
    certificateId: "SW/2026/08/000005",
  },
  {
    id: "WKF-20260901-T8VK2M",
    program_type: "zakat",
    programId: "prg-zakat-asnaf",
    programNama: "Zakat Maal Pemberdayaan 8 Asnaf",
    nominal: 3_250_000,
    biayaAdmin: 0,
    total: 3_250_000,
    namaWakif: "Hendra Kurniawan",
    emailWakif: "wakif@contoh.id",
    teleponWakif: "081234567006",
    atasNama: "sendiri",
    visibilitas: "anonim",
    vaNumber: "DEMO 7788 9900 0610",
    bank: "BSI",
    status: "paid",
    createdAt: "2026-09-01T04:10:00.000Z",
    expiresAt: "2026-09-02T04:10:00.000Z",
    paidAt: "2026-09-01T04:28:00.000Z",
    certificateId: "SW/2026/09/000006",
  },
];

export const SEED_CERTIFICATES: Certificate[] = SEED_TRANSACTIONS.map((t) => ({
  id: t.certificateId!,
  transactionId: t.id,
  programId: t.programId,
  programNama: t.programNama,
  program_type: t.program_type,
  namaPihak: t.atasNama === "orang-lain" && t.namaAtasNama ? t.namaAtasNama : t.namaWakif,
  nominal: t.nominal,
  tanggal: t.paidAt!,
  nazhir:
    SEED_PROGRAMS.find((p) => p.id === t.programId)?.nazhir ??
    "Nazhir Yayasan Khazanah Berkah Mulia",
}));

// Nomor urut sertifikat berikutnya (lanjut dari seed).
export const SEED_CERT_SEQ = SEED_CERTIFICATES.length; // -> 4
